import {
    AlertTriangleIcon,
    BackgroundIcon,
    BoldIcon,
    CheckIcon,
    CodeIcon,
    EyeIcon,
    EyedropperIcon,
    FolderIcon,
    FontIcon,
    GridIcon,
    HelpCircleIcon,
    InfoIcon,
    ItalicIcon,
    MusicIcon,
    OpenInNewIcon,
    PaintRollerIcon,
    PauseIcon,
    PlayFilledIcon,
    TextColorIcon,
    TextSizeIcon,
    TransparencyIcon,
    UnderlineIcon,
    XIcon,
} from '@canva/app-ui-kit';

export const IconData = [
    {
        id: 1,
        icon: CheckIcon,
        text: 'Check',
        cat: '',
    },
    {
        id: 2,
        icon: XIcon,
        text: 'X',
        cat: '',
    },
    {
        id: 3,
        icon: MusicIcon,
        text: 'Music',
        cat: '',
    },
    {
        id: 4,
        icon: PauseIcon,
        text: 'Pause',
        cat: '',
    },
    {
        id: 5,
        icon: PlayFilledIcon,
        text: 'Play Filled',
        cat: '',
    },
    {
        id: 6,
        icon: CodeIcon,
        text: 'Code',
        cat: '',
    },
    {
        id: 7,
        icon: AlertTriangleIcon,
        text: 'Alert triangle',
        cat: '',
    },
    {
        id: 8,
        icon: HelpCircleIcon,
        text: 'Help circle',
        cat: '',
    },
    {
        id: 9,
        icon: OpenInNewIcon,
        text: 'Open in new',
        cat: '',
    },
    {
        id: 10,
        icon: InfoIcon,
        text: 'Info',
        cat: '',
    },
    {
        id: 11,
        icon: EyeIcon,
        text: 'Eye',
        cat: '',
    },
    {
        id: 12,
        icon: FolderIcon,
        text: 'Folder',
        cat: '',
    },
    {
        id: 13,
        icon: GridIcon,
        text: 'Grid',
        cat: '',
    },
    {
        id: 14,
        icon: BoldIcon,
        text: 'Bold',
        cat: '',
    },
    {
        id: 15,
        icon: ItalicIcon,
        text: 'Italic',
        cat: '',
    },
    {
        id: 16,
        icon: UnderlineIcon,
        text: 'Underline',
        cat: '',
    },
    {
        id: 17,
        icon: PaintRollerIcon,
        text: 'Paint roller',
        cat: '',
    },
    {
        id: 18,
        icon: BackgroundIcon,
        text: 'Background',
        cat: '',
    },
    {
        id: 19,
        icon: EyedropperIcon,
        text: 'Eyedropper',
        cat: '',
    },
    {
        id: 20,
        icon: TransparencyIcon,
        text: 'Transparency',
        cat: '',
    },
    {
        id: 21,
        icon: FontIcon,
        text: 'Font',
        cat: '',
    },
    {
        id: 22,
        icon: TextColorIcon,
        text: 'Text color',
        cat: '',
    },
    {
        id: 23,
        icon: TextSizeIcon,
        text: 'Text size',
        cat: '',
    },
];
