export enum ComponentType {
    BUTTON = 'button',
    ICON_BUTTON = 'icon-button',
    PILL = 'pill',
    ALERT = 'alert',
    BADGE = 'badge',
    FORM_FIELD = 'form-field',
    CHECKBOX = 'checkbox',
    CHECKBOX_GROUP = 'checkbox-group',
    RADIO = 'radio',
    TEXT_INPUT = 'text-input',
    MULTILINE_INPUT = 'multiline-input',
    SEGMENTED_CONTROL = 'segmented-control',
    SLIDER = 'slider',
    NUMBER_INPUT = 'number-input',
    FILE_INPUT = 'file-input',
    SELECT = 'select',
    SWITCH = 'switch',
    SWATCH = 'swatch',
    COLOR_PICKER = 'color-picker',
    LOADING_INDICATOR = 'loading-indicator',
    PLACEHOLDER = 'placeholder',
    PROGRESS_BAR = 'progress-bar',
    AUDIO_CARD = 'audio-card',
    IMAGE_CARD = 'image-card',
    TYPOGRAPHY_CARD = 'typography-card',
    VIDEO_CARD = 'video-card',
    EMBED_CARD = 'embed-card',
    TITLE = 'title',
    TEXT = 'text',
    LINK = 'link',
    CATEGORY = 'category',
    OPTIONS_LIST = 'options-list',
    ICON_SELECTOR = 'icon-selector',
}

export enum OptionTypes {
    RADIO = 'radio',
    CHECKBOX = 'checkbox',
}
