import { Container } from 'src/models/containers.model';

export const containers: Container[] = [
    {
        list: '/assets/containers/list/editor-page.svg',
        main: '/assets/containers/main/editor-page.svg',
        label: 'Editor page',
        value: 'editor-page',
        width: 'full',
        align: 'left',
        SVGheight: 200,
    },
    {
        list: '/assets/containers/list/editor-page-lo-fi.svg',
        main: '/assets/containers/main/editor-page-lo-fi.svg',
        label: 'Editor page (Lo-fi)',
        value: 'editor-page-lo-fi',
        width: 'full',
        align: 'left',
        SVGheight: 200,
    },
    {
        list: '/assets/containers/list/editor-page-with-object-panel.svg',
        main: '/assets/containers/main/editor-page-with-object-panel.svg',
        label: 'Editor page with object panel',
        value: 'editor-page-with-object-panel',
        width: 'full',
        align: 'left',
        SVGheight: 200,
    },
    {
        list: '/assets/containers/list/editor-page-with-object-panel-lo-fi.svg',
        main: '/assets/containers/main/editor-page-with-object-panel-lo-fi.svg',
        label: 'Editor page with object panel (Lo-fi)',
        value: 'editor-page-with-object-panel-lo-fi',
        width: 'full',
        align: 'left',
        SVGheight: 200,
    },
    {
        list: '/assets/containers/list/editor-page-edit-panel.svg',
        main: '/assets/containers/main/editor-page-edit-panel.svg',
        label: 'Editor page with edit panel',
        value: 'editor-page-edit-panel',
        width: 'full',
        align: 'right',
        SVGheight: 200,
    },
    {
        list: '/assets/containers/list/editor-page-edit-panel-lo-fi.svg',
        main: '/assets/containers/main/editor-page-edit-panel-lo-fi.svg',
        label: 'Editor page with edit panel (Lo-fi)',
        value: 'editor-page-edit-panel-lo-fi',
        width: 'full',
        align: 'right',
        SVGheight: 200,
    },
    {
        list: '/assets/containers/list/editor-page-edit-panel-blank.svg',
        main: '/assets/containers/main/editor-page-edit-panel-blank.svg',
        label: 'Editor page with edit panel (Blank)',
        value: 'editor-page-edit-panel-blank',
        width: 'full',
        align: 'right',
        SVGheight: 200,
    },
    {
        list: '/assets/containers/list/home.svg',
        main: '/assets/containers/main/home.svg',
        label: 'Home page',
        value: 'home',
        width: 'full',
        align: 'left',
        SVGheight: 200,
    },
    {
        list: '/assets/containers/list/home-blank.svg',
        main: '/assets/containers/main/home-blank.svg',
        label: 'Home page (Blank)',
        value: 'home-blank',
        width: 'full',
        align: 'left',
        SVGheight: 200,
    },
    {
        list: '/assets/containers/list/home-lo-fi.svg',
        main: '/assets/containers/main/home-lo-fi.svg',
        label: 'Home page (Lo-fi)',
        value: 'home-lo-fi',
        width: 'full',
        align: 'left',
        SVGheight: 200,
    },
    {
        list: '/assets/containers/list/home-lo-fi-blank.svg',
        main: '/assets/containers/main/home-lo-fi-blank.svg',
        label: 'Home page (Lo-fi, Blank)',
        value: 'home-lo-fi-blank',
        width: 'full',
        align: 'left',
        SVGheight: 200,
    },
    {
        list: '/assets/containers/list/projects.svg',
        main: '/assets/containers/main/projects.svg',
        label: 'Projects',
        value: 'projects',
        width: 'full',
        align: 'left',
        SVGheight: 200,
    },
    {
        list: '/assets/containers/list/projects-lo-fi.svg',
        main: '/assets/containers/main/projects-lo-fi.svg',
        label: 'Projects (Lo-fi)',
        value: 'projects-lo-fi',
        width: 'full',
        align: 'left',
        SVGheight: 200,
    },
    {
        list: '/assets/containers/list/object-panel.svg',
        main: '/assets/containers/main/object-panel.svg',
        label: 'Object panel surface',
        value: 'object-panel',
        width: 'half',
        align: 'left',
        SVGheight: 400,
    },
    {
        list: '/assets/containers/list/object-panel-lo-fi.svg',
        main: '/assets/containers/main/object-panel-lo-fi.svg',
        label: 'Object panel surface (Lo-fi)',
        value: 'object-panel-lo-fi',
        width: 'half',
        align: 'left',
        SVGheight: 400,
    },
    {
        list: '/assets/containers/list/object-panel-mobile.svg',
        main: '/assets/containers/main/object-panel-mobile.svg',
        label: 'Object panel (Mobile)',
        value: 'object-panel-mobile',
        width: 'half',
        align: 'bottom-left',
        SVGheight: 400,
    },
    {
        list: '/assets/containers/list/object-panel-mobile-lo-fi.svg',
        main: '/assets/containers/main/object-panel-mobile-lo-fi.svg',
        label: 'Object panel (Mobile Lo-fi)',
        value: 'object-panel-mobile-lo-fi',
        width: 'half',
        align: 'bottom-left',
        SVGheight: 400,
    },
    {
        list: '/assets/containers/list/share-menu.svg',
        main: '/assets/containers/main/share-menu.svg',
        label: 'Share menu',
        value: 'share-menu',
        width: 'half',
        align: 'left',
        SVGheight: 400,
    },
    {
        list: '/assets/containers/list/share-menu-lo-fi.svg',
        main: '/assets/containers/main/share-menu-lo-fi.svg',
        label: 'Share menu (Lo-fi)',
        value: 'share-menu-lo-fi',
        width: 'half',
        align: 'left',
        SVGheight: 400,
    },
    {
        list: '/assets/containers/list/share-menu-blank.svg',
        main: '/assets/containers/main/share-menu-blank.svg',
        label: 'Share menu (Blank)',
        value: 'share-menu-blank',
        width: 'half',
        align: 'left',
        SVGheight: 400,
    },
    {
        list: '/assets/containers/list/edit-panel.svg',
        main: '/assets/containers/main/edit-panel.svg',
        label: 'Edit panel',
        value: 'edit-panel',
        width: 'half',
        align: 'left',
        SVGheight: 400,
    },
    {
        list: '/assets/containers/list/edit-panel-lo-fi.svg',
        main: '/assets/containers/main/edit-panel-lo-fi.svg',
        label: 'Edit panel (Lo-fi)',
        value: 'edit-panel-lo-fi',
        width: 'half',
        align: 'left',
        SVGheight: 400,
    },
    {
        list: '/assets/containers/list/edit-panel-blank.svg',
        main: '/assets/containers/main/edit-panel-blank.svg',
        label: 'Edit panel (Blank)',
        value: 'edit-panel-blank',
        width: 'half',
        align: 'left',
        SVGheight: 400,
    },
    {
        list: '/assets/containers/list/edit-header.svg',
        main: '/assets/containers/main/edit-header.svg',
        label: 'Editor header',
        value: 'edit-header',
        width: 'half',
        align: 'left',
        SVGheight: 40,
    },
    {
        list: '/assets/containers/list/edit-header-lo-fi.svg',
        main: '/assets/containers/main/edit-header-lo-fi.svg',
        label: 'Editor header (Lo-fi)',
        value: 'edit-header-lo-fi',
        width: 'half',
        align: 'left',
        SVGheight: 40,
    },
    {
        list: '/assets/containers/list/object-panel-tab.svg',
        main: '/assets/containers/main/object-panel-tab.svg',
        label: 'Object panel tabs',
        value: 'object-panel-tab',
        width: 'half',
        align: 'center',
        SVGheight: 400,
    },
    {
        list: '/assets/containers/list/object-panel-tab-lo-fi.svg',
        main: '/assets/containers/main/object-panel-tab-lo-fi.svg',
        label: 'Object panel tabs (Lo-fi)',
        value: 'object-panel-tab-lo-fi',
        width: 'half',
        align: 'center',
        SVGheight: 400,
    },
    {
        list: '/assets/containers/list/toolbar.svg',
        main: '/assets/containers/main/toolbar.svg',
        label: 'Toolbar',
        value: 'toolbar',
        width: 'half',
        align: 'left',
        SVGheight: 40,
    },
    {
        list: '/assets/containers/list/toolbar-lo-fi.svg',
        main: '/assets/containers/main/toolbar-lo-fi.svg',
        label: 'Toolbar (Lo-fi)',
        value: 'toolbar-lo-fi',
        width: 'half',
        align: 'left',
        SVGheight: 40,
    },
    {
        list: '/assets/containers/list/canvas.svg',
        main: '/assets/containers/main/canvas.svg',
        label: 'Canvas',
        value: 'canvas',
        width: 'half',
        align: 'left',
        SVGheight: 200,
    },
    {
        list: '/assets/containers/list/canvas-lo-fi.svg',
        main: '/assets/containers/main/canvas-lo-fi.svg',
        label: 'Canvas (Lo-fi)',
        value: 'canvas-lo-fi',
        width: 'half',
        align: 'left',
        SVGheight: 200,
    },
    {
        list: '/assets/containers/list/selection-handles.svg',
        main: '/assets/containers/main/selection-handles.svg',
        label: 'Selection handles',
        value: 'selection-handles',
        width: 'half',
        align: 'center',
        SVGheight: 200,
    },
];
