import {
    AlertTriangleIcon,
    AlignBottomIcon,
    AlignCenterIcon,
    AlignLeftIcon,
    AlignMiddleIcon,
    AlignRightIcon,
    AlignTopIcon,
    ArrowDownIcon,
    ArrowLeftIcon,
    ArrowRightIcon,
    ArrowUpIcon,
    BackgroundIcon,
    BoldIcon,
    CheckIcon,
    ChevronDownIcon,
    ChevronLeftIcon,
    ChevronRightIcon,
    ChevronUpIcon,
    CodeIcon,
    EyeIcon,
    EyedropperIcon,
    FlagIcon,
    FolderIcon,
    FontIcon,
    GridIcon,
    HelpCircleIcon,
    InfoIcon,
    ItalicIcon,
    LightBulbIcon,
    ListBulletLtrIcon,
    MusicIcon,
    OpenInNewIcon,
    PaintRollerIcon,
    PauseIcon,
    PlayFilledIcon,
    SpaceHorizontalIcon,
    SpaceVerticalIcon,
    TextColorIcon,
    TextSizeIcon,
    TransparencyIcon,
    UnderlineIcon,
    XIcon,
    TextAlignRightIcon,
    TextAlignLeftIcon,
    TextAlignCenterIcon,
    TextAlignJustifyIcon,
    MinusIcon,
    PlusIcon,
    CogIcon,
    CropIcon,
    CopyIcon,
    PencilIcon,
    TrashIcon,
    ImportIcon,
    ExportIcon,
    ReloadIcon,
    RotateIcon,
    SearchIcon,
    SortAscendingIcon,
    SortDescendingIcon,
    SortIcon,
    GridViewIcon,
    ClearIcon,
    SlidersIcon,
    FlipHorizontalIcon,
    FlipVerticalIcon,
    UndoIcon,
    RedoIcon,
    LockClosedIcon,
    LockOpenIcon,
} from '@canva/app-ui-kit';

import { Icon } from 'src/models/icons.model';

export const icons: Icon[] = [
    {
        value: 'check-icon',
        label: 'Check',
        Icon: CheckIcon,
    },
    {
        value: 'x-icon',
        label: 'X',
        Icon: XIcon,
    },
    {
        value: 'music-icon',
        label: 'Music',
        Icon: MusicIcon,
    },
    {
        value: 'pause-icon',
        label: 'Pause',
        Icon: PauseIcon,
    },
    {
        value: 'play-filled-icon',
        label: 'Play filled',
        Icon: PlayFilledIcon,
    },
    {
        value: 'code-icon',
        label: 'Code',
        Icon: CodeIcon,
    },
    {
        value: 'alert-triangle-icon',
        label: 'Alert triangle',
        Icon: AlertTriangleIcon,
    },
    {
        value: 'help-circle-icon',
        label: 'Help circle',
        Icon: HelpCircleIcon,
    },
    {
        value: 'open-in-new-icon',
        label: 'Open in new',
        Icon: OpenInNewIcon,
    },
    {
        value: 'info-icon',
        label: 'Info',
        Icon: InfoIcon,
    },
    {
        value: 'eye-icon',
        label: 'Eye',
        Icon: EyeIcon,
    },
    {
        value: 'folder-icon',
        label: 'Folder',
        Icon: FolderIcon,
    },
    {
        value: 'grvalue-icon',
        label: 'Grid icon',
        Icon: GridIcon,
    },
    {
        value: 'flag-icon',
        label: 'Flag',
        Icon: FlagIcon,
    },
    {
        value: 'light-bulb-icon',
        label: 'LightBulb',
        Icon: LightBulbIcon,
    },
    {
        value: 'bold-icon',
        label: 'Bold',
        Icon: BoldIcon,
    },
    {
        value: 'italic-icon',
        label: 'Italic',
        Icon: ItalicIcon,
    },
    {
        value: 'underline-icon',
        label: 'Underline',
        Icon: UnderlineIcon,
    },
    {
        value: 'paint-roller-icon',
        label: 'Paint roller',
        Icon: PaintRollerIcon,
    },
    {
        value: 'background-icon',
        label: 'Background',
        Icon: BackgroundIcon,
    },
    {
        value: 'eyedropper-icon',
        label: 'Eyedropper',
        Icon: EyedropperIcon,
    },
    {
        value: 'transparency-icon',
        label: 'Transparency',
        Icon: TransparencyIcon,
    },
    {
        value: 'font-icon',
        label: 'Font',
        Icon: FontIcon,
    },
    {
        value: 'text-color-icon',
        label: 'Text color',
        Icon: TextColorIcon,
    },
    {
        value: 'text-size-icon',
        label: 'Text size',
        Icon: TextSizeIcon,
    },
    {
        value: 'list-bullet-ltr-icon',
        label: 'List bulleter ',
        Icon: ListBulletLtrIcon,
    },
    {
        value: 'arrow-up-icon',
        label: 'Arrow up',
        Icon: ArrowUpIcon,
    },
    {
        value: 'arrow-down-icon',
        label: 'Arrow down',
        Icon: ArrowDownIcon,
    },
    {
        value: 'arrow-left-icon',
        label: 'Arrow left',
        Icon: ArrowLeftIcon,
    },
    {
        value: 'arrow-rigt-icon',
        label: 'Arrow right',
        Icon: ArrowRightIcon,
    },
    {
        value: 'chevron-up-icon',
        label: 'Chevron up',
        Icon: ChevronUpIcon,
    },
    {
        value: 'chevron-down-icon',
        label: 'Chevron down',
        Icon: ChevronDownIcon,
    },
    {
        value: 'chevron-left-icon',
        label: 'Chevron left',
        Icon: ChevronLeftIcon,
    },
    {
        value: 'chevron-right-icon',
        label: 'Chevron right',
        Icon: ChevronRightIcon,
    },
    {
        value: 'align-top-icon',
        label: 'Align top',
        Icon: AlignTopIcon,
    },
    {
        value: 'align-bottom-icon',
        label: 'Align bottom',
        Icon: AlignBottomIcon,
    },
    {
        value: 'align-middle-icon',
        label: 'Align middle',
        Icon: AlignMiddleIcon,
    },
    {
        value: 'align-left-icon',
        label: 'Align left',
        Icon: AlignLeftIcon,
    },
    {
        value: 'align-right-icon',
        label: 'Align right',
        Icon: AlignRightIcon,
    },
    {
        value: 'align-center-icon',
        label: 'Align center',
        Icon: AlignCenterIcon,
    },
    {
        value: 'space-horizontal-icon',
        label: 'Space horizontal',
        Icon: SpaceHorizontalIcon,
    },
    {
        value: 'space-vertical-icon',
        label: 'Space vertical',
        Icon: SpaceVerticalIcon,
    },
    {
        value: 'text-align-right-icon',
        label: 'Text align right',
        Icon: TextAlignRightIcon,
    },
    {
        value: 'text-align-left-icon',
        label: 'Text align left',
        Icon: TextAlignLeftIcon,
    },
    {
        value: 'text-align-center-icon',
        label: 'Text align center',
        Icon: TextAlignCenterIcon,
    },
    {
        value: 'text-align-justify-icon',
        label: 'Text align justify',
        Icon: TextAlignJustifyIcon,
    },
    {
        value: 'minus-icon',
        label: 'Minus',
        Icon: MinusIcon,
    },
    {
        value: 'plus-icon',
        label: 'Plus',
        Icon: PlusIcon,
    },
    {
        value: 'cog-icon',
        label: 'Cog',
        Icon: CogIcon,
    },
    {
        value: 'crop-icon',
        label: 'Crop',
        Icon: CropIcon,
    },
    {
        value: 'copy-icon',
        label: 'Copy',
        Icon: CopyIcon,
    },
    {
        value: 'pencil-icon',
        label: 'Pencil',
        Icon: PencilIcon,
    },
    {
        value: 'trash-icon',
        label: 'Trash',
        Icon: TrashIcon,
    },
    {
        value: 'import-icon',
        label: 'Import',
        Icon: ImportIcon,
    },
    {
        value: 'export-icon',
        label: 'Export',
        Icon: ExportIcon,
    },
    {
        value: 'reload-icon',
        label: 'Reload',
        Icon: ReloadIcon,
    },
    {
        value: 'rotate-icon',
        label: 'Rotate',
        Icon: RotateIcon,
    },
    {
        value: 'search-icon',
        label: 'Search',
        Icon: SearchIcon,
    },
    {
        value: 'sort-ascending-icon',
        label: 'Sort ascending',
        Icon: SortAscendingIcon,
    },
    {
        value: 'sort-descending-icon',
        label: 'Sort descending',
        Icon: SortDescendingIcon,
    },
    {
        value: 'sort-icon',
        label: 'Sort',
        Icon: SortIcon,
    },
    {
        value: 'grid-view-icon',
        label: 'Grid view',
        Icon: GridViewIcon,
    },
    {
        value: 'clear-icon',
        label: 'Clear',
        Icon: ClearIcon,
    },
    {
        value: 'sliders-icon',
        label: 'Sliders',
        Icon: SlidersIcon,
    },
    {
        value: 'flip-horizontal-icon',
        label: 'Flip horizontal',
        Icon: FlipHorizontalIcon,
    },
    {
        value: 'flip-vertical-icon',
        label: 'Flip vertical',
        Icon: FlipVerticalIcon,
    },
    {
        value: 'undo-icon',
        label: 'Undo',
        Icon: UndoIcon,
    },
    {
        value: 'redo-icon',
        label: 'Redo',
        Icon: RedoIcon,
    },
    {
        value: 'lock-closed-icon',
        label: 'Lock closed',
        Icon: LockClosedIcon,
    },
    {
        value: 'lock-open-icon',
        label: 'Lock open',
        Icon: LockOpenIcon,
    },
];
