import {
    AlertTriangleIcon,
    AlignBottomIcon,
    AlignCenterIcon,
    AlignLeftIcon,
    AlignMiddleIcon,
    AlignRightIcon,
    AlignTopIcon,
    ArrowDownIcon,
    ArrowLeftIcon,
    ArrowRightIcon,
    ArrowUpIcon,
    BackgroundIcon,
    BoldIcon,
    CheckIcon,
    ChevronDownIcon,
    ChevronLeftIcon,
    ChevronRightIcon,
    ChevronUpIcon,
    CodeIcon,
    EyeIcon,
    EyedropperIcon,
    FlagIcon,
    FolderIcon,
    FontIcon,
    GridIcon,
    HelpCircleIcon,
    InfoIcon,
    ItalicIcon,
    LightBulbIcon,
    ListBulletLtrIcon,
    MusicIcon,
    OpenInNewIcon,
    PaintRollerIcon,
    PauseIcon,
    PlayFilledIcon,
    SpaceHorizontalIcon,
    SpaceVerticalIcon,
    TextColorIcon,
    TextSizeIcon,
    TransparencyIcon,
    UnderlineIcon,
    XIcon,
} from '@canva/app-ui-kit';
import { Icon } from 'src/models/icons.model';

export const icons: Icon[] = [
    {
        id: 'check-icon',
        icon: CheckIcon,
        name: 'Check',
    },
    {
        id: 'x-icon',
        icon: XIcon,
        name: 'X',
    },
    {
        id: 'music-icon',
        icon: MusicIcon,
        name: 'Music',
    },
    {
        id: 'pause-icon',
        icon: PauseIcon,
        name: 'Pause',
    },
    {
        id: 'play-filled-icon',
        icon: PlayFilledIcon,
        name: 'Play Filled',
    },
    {
        id: 'code-icon',
        icon: CodeIcon,
        name: 'Code',
    },
    {
        id: 'alert-triangle-icon',
        icon: AlertTriangleIcon,
        name: 'Alert triangle',
    },
    {
        id: 'help-circle-icon',
        icon: HelpCircleIcon,
        name: 'Help circle',
    },
    {
        id: 'open-in-new-icon',
        icon: OpenInNewIcon,
        name: 'Open in new',
    },
    {
        id: 'info-icon',
        icon: InfoIcon,
        name: 'Info',
    },
    {
        id: 'eye-icon',
        icon: EyeIcon,
        name: 'Eye',
    },
    {
        id: 'folder-icon',
        icon: FolderIcon,
        name: 'Folder',
    },
    {
        id: 'grid-icon',
        icon: GridIcon,
        name: 'Grid',
    },
    {
        id: 'flag-icon',
        icon: FlagIcon,
        name: 'Flag',
    },
    {
        id: 'light-bulb-icon',
        icon: LightBulbIcon,
        name: 'LightBulb',
    },
    {
        id: 'bold-icon',
        icon: BoldIcon,
        name: 'Bold',
    },
    {
        id: 'italic-icon',
        icon: ItalicIcon,
        name: 'Italic',
    },
    {
        id: 'underline-icon',
        icon: UnderlineIcon,
        name: 'Underline',
    },
    {
        id: 'paint-roller-icon',
        icon: PaintRollerIcon,
        name: 'Paint roller',
    },
    {
        id: 'background-icon',
        icon: BackgroundIcon,
        name: 'Background',
    },
    {
        id: 'eyedropper-icon',
        icon: EyedropperIcon,
        name: 'Eyedropper',
    },
    {
        id: 'transparency-icon',
        icon: TransparencyIcon,
        name: 'Transparency',
    },
    {
        id: 'font-icon',
        icon: FontIcon,
        name: 'Font',
    },
    {
        id: 'text-color-icon',
        icon: TextColorIcon,
        name: 'Text color',
    },
    {
        id: 'text-size-icon',
        icon: TextSizeIcon,
        name: 'Text size',
    },
    {
        id: 'list-bullet-ltr-icon',
        icon: ListBulletLtrIcon,
        name: 'List bulleter ',
    },
    {
        id: 'arrow-up-icon',
        icon: ArrowUpIcon,
        name: 'Arrow up',
    },
    {
        id: 'arrow-down-icon',
        icon: ArrowDownIcon,
        name: 'Arrow down',
    },
    {
        id: 'arrow-left-icon',
        icon: ArrowLeftIcon,
        name: 'Arrow left',
    },
    {
        id: 'arrow-rigt-icon',
        icon: ArrowRightIcon,
        name: 'Arrow right',
    },
    {
        id: 'chevron-up-icon',
        icon: ChevronUpIcon,
        name: 'Chevron up',
    },
    {
        id: 'chevron-down-icon',
        icon: ChevronDownIcon,
        name: 'Chevron down',
    },
    {
        id: 'chevron-left-icon',
        icon: ChevronLeftIcon,
        name: 'Chevron left',
    },
    {
        id: 'chevron-right-icon',
        icon: ChevronRightIcon,
        name: 'Chevron right',
    },
    {
        id: 'align-top-icon',
        icon: AlignTopIcon,
        name: 'Align top',
    },
    {
        id: 'align-bottom-icon',
        icon: AlignBottomIcon,
        name: 'Align bottom',
    },
    {
        id: 'align-middle-icon',
        icon: AlignMiddleIcon,
        name: 'Align middle',
    },
    {
        id: 'align-left-icon',
        icon: AlignLeftIcon,
        name: 'Align left',
    },
    {
        id: 'align-right-icon',
        icon: AlignRightIcon,
        name: 'Align right',
    },
    {
        id: 'align-center-icon',
        icon: AlignCenterIcon,
        name: 'Align center',
    },
    {
        id: 'space-horizontal-icon',
        icon: SpaceHorizontalIcon,
        name: 'Space horizontal',
    },
    {
        id: 'space-vertical-icon',
        icon: SpaceVerticalIcon,
        name: 'Space vertical',
    },
];
